kind: pipeline
name: docker-terragrunt

steps:
- name: build and publish
  image: plugins/docker
  dockerfile: Dockerfile
  environment:
    TERRAFORM_VERSION: 0.14.0
    TERRAGRUNT_VERSION: 0.27.0
  settings:
    repo: wirelab/docker-terragrunt
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_TOKEN
    build_args_from_env:
      - TERRAFORM_VERSION
      - TERRAGRUNT_VERSION
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
