matrix:
  TERRAFORM_VERSION:
    - 0.12.25
  TERRAGRUNT_VERSION:
    - 0.23.18

kind: pipeline
name: docker-terragrunt

steps:
- name: docker-terragrunt
  image: plugins/docker
  dockerfile: Dockerfile
  settings:
    username:
      from_secret: DOCKERHUB_USERNAME
    auth:
      from_secret: DOCKERHUB_TOKEN
    repo: wirelab/docker-terragrunt
    auto_tag: true
    build_args:
      - TERRAFORM_VERSION=${TERRAFORM_VERSION}
      - TERRAGRUNT_VERSION=${TERRAGRUNT_VERSION}
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
      - v${TERRAGRUNT_VERSION}
