kind: pipeline
name: docker-terragrunt

steps:
- name: build and publish
  image: docker:17.09.0-ce
  dockerfile: Dockerfile
  environment:
    TERRAFORM_VERSION: 0.13.4
    TERRAGRUNT_VERSION: 0.25.4
  settings:
    repo: wirelab/docker-terragrunt
    username:
      from_secret: DOCKERHUB_USERNAME
    auth:
      from_secret: DOCKERHUB_TOKEN
    build_args_from_env:
      - TERRAFORM_VERSION
      - TERRAGRUNT_VERSION
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
      - v${TERRAGRUNT_VERSION}
    when:
      event: push
